'''
Ensure CSV file (subject_ids.csv) follows this structure:

DatasetName
SUBJ01
SUBJ02
SUBJ03
...

'''


# # Generated by Selenium IDE
# import pytest
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# class TestTestcreatesubjects():
#   def setup_method(self, method):
#     self.driver = webdriver.Chrome()
#     self.vars = {}
  
#   def teardown_method(self, method):
#     self.driver.quit()
  
#   def test_testcreatesubjects(self):
#     self.driver.get("https://addbiomechanics.org/")
#     self.driver.set_window_size(1150, 1043)
#     self.driver.find_element(By.CSS_SELECTOR, ".gap-3").click()
#     self.driver.find_element(By.CSS_SELECTOR, "input").click()
#     self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("test-criekinge")
#     self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
#     self.driver.find_element(By.LINK_TEXT, "test-criekinge").click()
#     self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").click()
#     self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").send_keys("SUBJ01")
#     self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
  
import pytest
import csv
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestTestcreatesubjects():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_testcreatesubjects(self):
        self.driver.get("https://addbiomechanics.org/") # open the website
        self.driver.set_window_size(1150, 1043) # setting window size
        
        # Login (replace with your login logic)
        self.driver.find_element(By.CSS_SELECTOR, ".gap-3").click()
        self.driver.find_element(By.CSS_SELECTOR, "input").click()
        self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("test-criekinge")
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
        
        # Navigate to the dataset
        dataset_name = None  # Will be updated after reading the CSV
        with open('selenium_automation/gait_subjectid_criekinge.csv', 'r') as file:
            csv_reader = csv.reader(file)
            for i, row in enumerate(csv_reader):
                if i == 0:
                    # The first row contains the dataset name
                    dataset_name = row[0]
                    self.driver.find_element(By.LINK_TEXT, dataset_name).click()
                else:
                    # Subsequent rows contain subject IDs
                    subject_id = row[0]
                    
                    # Create a new folder for the subject ID
                    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").click()
                    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").clear()
                    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").send_keys(subject_id)
                    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
                    
                    # Optional: Add a wait to ensure the folder is created before proceeding
                    WebDriverWait(self.driver, 10).until(
                        EC.presence_of_element_located((By.LINK_TEXT, subject_id))
                    )

